### PR TITLE
Navigation update

### PR DESCRIPTION
**Pull request by phillipbarron**
## What does this change?

Uses Material UIs AppBar component navigation - no functional change other than responsive menus. Moving toward a UI more consistent with the existing suite of Guardian tooling

The User icon is a. place-holder at this stage. The intent is to pull user info and an appropriate avatar from the Google account.

## How to test

Check it out, have a click about and assure yourself that all is well

## Have we considered potential risks?

Screenshot 2023-04-27 at 12 08 14

Screenshot 2023-04-27 at 12 08 29
4-9434-33a76ac9cac1.png)

Screenshot 2023-04-27 at 12 08 41

### CODE REVIEW

**Comment by codingWithRach** [comment]
On your final screenshot, is there an accessibility issue with the grey NEWSLETTERS on the blue background?

**Comment by phillipbarron** [comment]
> On your final screenshot, is there an accessibility issue with the grey NEWSLETTERS on the blue background?

Could be - would you object to a merge as is and then an update after some UX guidance?

**Review by codingWithRach — APPROVED** [review]
Looks really good!

**Comment by codingWithRach** [comment]
> > On your final screenshot, is there an accessibility issue with the grey NEWSLETTERS on the blue background?
> 
> Could be - would you object to a merge as is and then an update after some UX guidance?

Absolutely - go for it.  I just ran a Lighthouse report and it didn't come up with any problems, but I'm surprised by that.  But it's a whole area that we haven't yet addressed so it can all be done together :-)

**Pull request merged**
