### PR TITLE
Update route / actions grouping and Nav styling

### PR DESCRIPTION
**Pull request by phillipbarron**
## What does this change?

Aligns the routes with the menu options and groups actions based on state. 

Adds an update to the Nav styling to make make it clearer which section you are in

## How to test

Make sure everything still works. Local testing looks ok but it would be good to have a  second pair of eyes on this

## Have we considered potential risks?

Yep

## Images

Screenshot 2023-07-24 at 07 43 19
ally only applicable to UI changes, check the boxes if you are satisfied that your changes pass these tests -->

### CODE REVIEW

**Comment by dblatcher** [comment]
Afraid's one more `NavigationButton` to update in "apps/newsletters-ui/src/app/components/views/RenderingOptionsView.tsx"

**Comment by dblatcher** [comment]
We may need to add '/launched' and '/launched/*' to the paths handled by `handleUiRequest` in "apps/newsletters-api/src/register-ui-server.ts" - we needed to do this in production so the browsing directly (as opposed to using a navigation action within the app) to a page in the UI will be handled by the router.

**Comment by phillipbarron** [comment]
> RenderingOptionsView

Ahh interesting - thanks - that was not on my radar at all
let me check

**Comment by phillipbarron** [comment]
> We may need to add '/launched' and '/launched/*' to the paths handled by `handleUiRequest` in "apps/newsletters-api/src/register-ui-server.ts" - we needed to do this in production so the browsing directly (as opposed to using a navigation action within the app) to a page in the UI will be handled by the router.

**Review by dblatcher — APPROVED** [review]

**Pull request merged**
